/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-10-05 02:34:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Cinema A Entertainment Category Flat Bootstrap Responsive Website Template</title>\n");
      out.write("        <link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\n");
      out.write("        <!-- Custom Theme files -->\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("        <!-- Custom Theme files -->\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\n");
      out.write("        <!-- Custom Theme files -->\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("        <meta name=\"keywords\" content=\"Cinema Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, \n");
      out.write("              Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design\" />\n");
      out.write("        <script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\n");
      out.write("        <!--webfont-->\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- header-section-starts -->\n");
      out.write("        <div class=\"full\">\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\n");
      out.write("                <div class=\"main\">\n");
      out.write("                \n");
      out.write("                \t<div class=\"header\">\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("\t\t\t<div class=\"header-info\">\n");
      out.write("\t\t\t\t<h1>BIG HERO 6</h1>\n");
      out.write("\t\t\t\t<p class=\"age\"><a href=\"#\">All Age</a> Don Hall, Chris Williams</p>\n");
      out.write("\t\t\t\t<p class=\"review\">Rating\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: &nbsp;&nbsp;  8,5/10</p>\n");
      out.write("\t\t\t\t<p class=\"review reviewgo\">Genre\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : &nbsp;&nbsp; Animation, Action, Comedy</p>\n");
      out.write("\t\t\t\t<p class=\"review\">Release &nbsp;&nbsp;&nbsp;&nbsp;: &nbsp;&nbsp; 7 November 2014</p>\n");
      out.write("\t\t\t\t<p class=\"special\">The special bond that develops between plus-sized inflatable robot Baymax, and prodigy Hiro Hamada, who team up with a group of friends to form a band of high-tech heroes.</p>\n");
      out.write("\t\t\t\t<a class=\"video\" href=\"#\"><i class=\"video1\"></i>WATCH TRAILER</a>\n");
      out.write("\t\t\t\t<a class=\"book\" href=\"login.jsp\"><i class=\"book1\"></i>BOOK TICKET</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("                    <div class=\"review-slider\">\n");
      out.write("                        <ul id=\"flexiselDemo1\">\n");
      out.write("                            <li><img src=\"images/r1.jpg\" alt=\"\"/></li>\n");
      out.write("                            <li><img src=\"images/r2.jpg\" alt=\"\"/></li>\n");
      out.write("                            <li><img src=\"images/r3.jpg\" alt=\"\"/></li>\n");
      out.write("                            <li><img src=\"images/r4.jpg\" alt=\"\"/></li>\n");
      out.write("                            <li><img src=\"images/r5.jpg\" alt=\"\"/></li>\n");
      out.write("                            <li><img src=\"images/r6.jpg\" alt=\"\"/></li>\n");
      out.write("                        </ul>\n");
      out.write("                        <script type=\"text/javascript\">\n");
      out.write("                            $(window).load(function () {\n");
      out.write("\n");
      out.write("                                $(\"#flexiselDemo1\").flexisel({\n");
      out.write("                                    visibleItems: 6,\n");
      out.write("                                    animationSpeed: 1000,\n");
      out.write("                                    autoPlay: true,\n");
      out.write("                                    autoPlaySpeed: 3000,\n");
      out.write("                                    pauseOnHover: false,\n");
      out.write("                                    enableResponsiveBreakpoints: true,\n");
      out.write("                                    responsiveBreakpoints: {\n");
      out.write("                                        portrait: {\n");
      out.write("                                            changePoint: 480,\n");
      out.write("                                            visibleItems: 2\n");
      out.write("                                        },\n");
      out.write("                                        landscape: {\n");
      out.write("                                            changePoint: 640,\n");
      out.write("                                            visibleItems: 3\n");
      out.write("                                        },\n");
      out.write("                                        tablet: {\n");
      out.write("                                            changePoint: 768,\n");
      out.write("                                            visibleItems: 4\n");
      out.write("                                        }\n");
      out.write("                                    }\n");
      out.write("                                });\n");
      out.write("                            });\n");
      out.write("                        </script>\n");
      out.write("                        <script type=\"text/javascript\" src=\"js/jquery.flexisel.js\"></script>\t\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"video\">\n");
      out.write("                        <iframe  src=\"https://www.youtube.com/embed/2LqzF5WauAw\" frameborder=\"0\" allowfullscreen></iframe>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"news\">\n");
      out.write("                        <div class=\"col-md-6 news-left-grid\">\n");
      out.write("                            <h3>Don’t be late,</h3>\n");
      out.write("                            <h2>Book your ticket now!</h2>\n");
      out.write("                            <h4>Easy, simple & fast.</h4>\n");
      out.write("                            <a href=\"../src/java/com/g5cinemamovie/controller/LoginServlet1.java\"><i class=\"book\"></i>BOOK TICKET</a>\n");
      out.write("                            \n");
      out.write("                            <p>Get Discount up to <strong>10%</strong> if you are a member!</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-6 news-right-grid\">\n");
      out.write("                            <h3>News</h3>\n");
      out.write("                            <div class=\"news-grid\">\n");
      out.write("                                <h5>Lorem Ipsum Dolor Sit Amet</h5>\n");
      out.write("                                <label>Nov 11 2014</label>\n");
      out.write("                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"news-grid\">\n");
      out.write("                                <h5>Lorem Ipsum Dolor Sit Amet</h5>\n");
      out.write("                                <label>Nov 11 2014</label>\n");
      out.write("                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>\n");
      out.write("                            </div>\n");
      out.write("                            <a class=\"more\" href=\"#\">MORE</a>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"clearfix\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"more-reviews\">\n");
      out.write("                        <ul id=\"flexiselDemo2\">\n");
      out.write("                            <li><img src=\"images/m1.jpg\" alt=\"\"/></li>\n");
      out.write("                            <li><img src=\"images/m2.jpg\" alt=\"\"/></li>\n");
      out.write("                            <li><img src=\"images/m3.jpg\" alt=\"\"/></li>\n");
      out.write("                            <li><img src=\"images/m4.jpg\" alt=\"\"/></li>\n");
      out.write("                        </ul>\n");
      out.write("                        <script type=\"text/javascript\">\n");
      out.write("                            $(window).load(function () {\n");
      out.write("\n");
      out.write("                                $(\"#flexiselDemo2\").flexisel({\n");
      out.write("                                    visibleItems: 4,\n");
      out.write("                                    animationSpeed: 1000,\n");
      out.write("                                    autoPlay: true,\n");
      out.write("                                    autoPlaySpeed: 3000,\n");
      out.write("                                    pauseOnHover: false,\n");
      out.write("                                    enableResponsiveBreakpoints: true,\n");
      out.write("                                    responsiveBreakpoints: {\n");
      out.write("                                        portrait: {\n");
      out.write("                                            changePoint: 480,\n");
      out.write("                                            visibleItems: 2\n");
      out.write("                                        },\n");
      out.write("                                        landscape: {\n");
      out.write("                                            changePoint: 640,\n");
      out.write("                                            visibleItems: 3\n");
      out.write("                                        },\n");
      out.write("                                        tablet: {\n");
      out.write("                                            changePoint: 768,\n");
      out.write("                                            visibleItems: 3\n");
      out.write("                                        }\n");
      out.write("                                    }\n");
      out.write("                                });\n");
      out.write("                            });\n");
      out.write("                        </script>\n");
      out.write("                        <script type=\"text/javascript\" src=\"js/jquery.flexisel.js\"></script>\t\n");
      out.write("                    </div>\t\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"clearfix\"></div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
